benchmark:
  name: "Stanford Cars"
  version: "1.0"
  description: "Fine-grained classification of 196 car classes"
  category: "vision"
  paper: "Krause et al., 2013"
  official_url: "https://ai.stanford.edu/~jkrause/cars/car_dataset.html"

dataset:
  source: "huggingface"
  path: "stanford_cars"
  cache_dir: "${CACHE_DIR}/datasets/cars"

subtasks:
  - name: "default"
    task_type: "image_classification"
    dataset_config: "default"
    metrics: ["accuracy", "f1_macro"]
    input_columns: ["image"]
    label_column: "label"

evaluation:
  batch_size: 32
  max_sequence_length: 224
  num_workers: 4
  use_cache: true
  cache_predictions: true

output:
  format: "json"
  save_raw_predictions: true
  save_per_sample_metrics: false
  aggregate_subtasks: false
