benchmark:
  name: "Oxford-IIIT Pet Dataset"
  version: "1.0"
  description: "Fine-grained classification of 37 pet breeds"
  category: "vision"
  paper: "Parkhi et al., 2012"
  official_url: "https://www.robots.ox.ac.uk/~vgg/data/pets/"

dataset:
  source: "huggingface"
  path: "oxford_iiit_pet"
  cache_dir: "${CACHE_DIR}/project_datasets/pets"

subtasks:
  - name: "default"
    task_type: "image_classification"
    dataset_config: "default"
    metrics: ["accuracy", "f1_macro"]
    input_columns: ["image"]
    label_column: "label"

evaluation:
  batch_size: 32
  max_sequence_length: 224
  num_workers: 4
  use_cache: true
  cache_predictions: true

output:
  format: "json"
  save_raw_predictions: true
  save_per_sample_metrics: false
  aggregate_subtasks: false
