# XOR-TyDiQA Benchmark Configuration

benchmark:
  name: "multilingual/xor_tydiqa"
  version: "1.0"
  description: "Cross-lingual Open-Retrieval Question Answering."
  category: "multilingual"
  paper: "Asai et al., 2021"
  official_url: "https://nlp.cs.washington.edu/xorqa/"

dataset:
  name: "xor_tydi_qa"
  source: "huggingface"
  path: "xor_tydi_qa"
  cache_dir: "/root/benchmarks/universal-model-benchmarks/datasets/cache"

subtasks:
  - name: "default"
    task_type: "extractive_qa"
    dataset_config: "default"
    metrics: ["f1", "exact_match"]
    input_columns: ["question", "context"]
    label_column: "answers"

evaluation:
  batch_size: 8
  use_cache: true

output:
  format: "json"
  save_raw_predictions: false
  aggregate_subtasks: false
  output_dir: "/root/benchmarks/universal-model-benchmarks/results/raw"
